# -*- coding: utf-8 -*-
"""DPEL Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s-8039Od37cpfzANEXB_PGPxMM44FR3q

#Introduction

Alzheimer MRI 4 Classes – Preprocessing & Exploratory Data Analysis (EDA)
"""

# This notebook demonstrates dataset preparation for classifying MRI scans into
# four stages of Alzheimer's disease:
# - Non-Demented
# - Very Mild Demented
# - Mild Demented
# - Moderate Demented

### Objectives
# 1. Understand dataset size, structure, and imbalance.
# 2. Apply preprocessing (resizing, normalization).
# 3. Perform data augmentation to improve class balance.
# 4. Visualize dataset distribution and samples.
# 5. Summarize key findings before model training.

# 📝 Problem Statement

# Alzheimer’s disease is a progressive neurodegenerative disorder that leads to memory loss and cognitive decline.
# Early detection and accurate classification of disease severity are crucial for diagnosis and treatment planning.

# The goal of this project is to classify brain MRI images into different stages of Alzheimer’s disease —
# - Non-Demented
# - Very Mild Demented
# - Mild Demented
# - Moderate Demented
# using data preprocessing, augmentation, and exploratory data analysis (EDA) techniques.

# This involves:
# Preprocessing MRI images (resizing, normalization, augmentation) to prepare them for model training.
# Exploring the dataset through visualizations to understand class distributions and dataset imbalance.
# Ensuring fair evaluation of models using stratified k-fold cross-validation.

"""#Setup and Data Extraction"""

import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
import pandas as pd
import numpy as np
import os

# 2) Unzip to /content/data/alz  (quotes handle spaces in the filename)
!mkdir -p /content/data/alz
!unzip -q "/content/Alzheimer Dataset.zip" -d /content/data/alz

# (Optional) See what's inside
!unzip -l "/content/Alzheimer Dataset.zip" | head -n 40

# Set the base directory to the extracted images
BASE_DIR = '/content/data/alz/Alzheimer_s Dataset/'
print("Base directory for images:", BASE_DIR)

"""#Defining Data Directories

Now that the image data is unzipped, we can define the paths to the training and testing directories.
"""

train_dir = os.path.join(BASE_DIR, 'train')
test_dir = os.path.join(BASE_DIR, 'test')

print("Training directory:", train_dir)
print("Testing directory:", test_dir)

"""#Data Preprocessing and Augmentation with Validation Split

Next, we will create ImageDataGenerator instances for both training and testing sets. This will handle the loading, preprocessing, and augmentation (for training data) of the images.
"""

# =======================
# Cell 1: Setup + Preprocessing
# =======================

import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
import os

# Define image dimensions and batch size
IMG_WIDTH = 224
IMG_HEIGHT = 224
BATCH_SIZE = 32

# Training data generator (with augmentation)
train_datagen = ImageDataGenerator(
    rescale=1./255,            # Normalize pixel values
    rotation_range=45,         # Random rotations
    zoom_range=0.2,            # Random zoom
    horizontal_flip=True,      # Flip images left-right
    validation_split=0.2       # Reserve 20% of training set for validation
)

# Testing data generator (no augmentation, only rescaling)
test_datagen = ImageDataGenerator(rescale=1./255)

# Flow training images
train_generator = train_datagen.flow_from_directory(
    directory=train_dir,
    target_size=(IMG_HEIGHT, IMG_WIDTH),
    color_mode='grayscale',     # MRI is grayscale (1 channel)
    class_mode='categorical',   # Multi-class classification
    batch_size=BATCH_SIZE,
    subset='training',
    shuffle=True
)

# Flow validation images
val_generator = train_datagen.flow_from_directory(
    directory=train_dir,
    target_size=(IMG_HEIGHT, IMG_WIDTH),
    color_mode='grayscale',
    class_mode='categorical',
    batch_size=BATCH_SIZE,
    subset='validation',
    shuffle=True
)

# Flow test images
test_generator = test_datagen.flow_from_directory(
    directory=test_dir,
    target_size=(IMG_HEIGHT, IMG_WIDTH),
    color_mode='grayscale',
    class_mode='categorical',
    batch_size=BATCH_SIZE,
    shuffle=False
)

print("Training batches:", len(train_generator))
print("Validation batches:", len(val_generator))
print("Testing batches:", len(test_generator))
print("Class labels:", train_generator.class_indices)

# Define image dimensions and batch size
IMG_WIDTH = 128
IMG_HEIGHT = 128
BATCH_SIZE = 32

# Create ImageDataGenerator for training data with augmentation
train_image_generator = ImageDataGenerator(
    rescale=1./255,
    rotation_range=45,
    zoom_range=0.2,
    horizontal_flip=True,
    fill_mode='nearest'
)

# Create ImageDataGenerator for testing data (only rescaling)
test_image_generator = ImageDataGenerator(rescale=1./255)

# Create data generators
train_data_gen = train_image_generator.flow_from_directory(
    batch_size=BATCH_SIZE,
    directory=train_dir,
    target_size=(IMG_HEIGHT, IMG_WIDTH),
    color_mode='grayscale',
    class_mode='categorical' # Use 'categorical' for multi-class classification
)

test_data_gen = test_image_generator.flow_from_directory(
    batch_size=BATCH_SIZE,
    directory=test_dir,
    target_size=(IMG_HEIGHT, IMG_WIDTH),
    class_mode='categorical' # Use 'categorical' for multi-class classification
)

print("Number of training batches:", len(train_data_gen))
print("Number of testing batches:", len(test_data_gen))
print("Class labels:", train_data_gen.class_indices)

# Directory where dataset is stored
# Structure should be like:
# Alzheimer_Dataset/
#   ├── train/
#   │   ├── MildDemented/
#   │   ├── ModerateDemented/
#   │   ├── NonDemented/
#   │   └── VeryMildDemented/
#   └── test/ ...

train_dir = "/content/data/alz/Alzheimer_s Dataset/train"
test_dir = "/content/data/alz/Alzheimer_s Dataset/test"

# Pre-processing: Resize to 224x224 and Normalize (rescale=1./255)
train_datagen = ImageDataGenerator(
    rescale=1./255,   # Normalization
    validation_split=0.2  # Split training into train/validation
)

train_generator = train_datagen.flow_from_directory(
    train_dir,
    target_size=(224, 224),  # Resizing
    batch_size=32,
    class_mode="categorical",
    subset="training"
)

val_generator = train_datagen.flow_from_directory(
    train_dir,
    target_size=(224, 224),
    batch_size=32,
    class_mode="categorical",
    subset="validation"
)

# Augmentation Generator
aug_datagen = ImageDataGenerator(
    rescale=1./255,
    rotation_range=20,       # Rotate images
    width_shift_range=0.2,   # Horizontal shift
    height_shift_range=0.2,  # Vertical shift
    zoom_range=0.2,          # Zoom
    horizontal_flip=True,    # Flip horizontally
    fill_mode="nearest",     # Fill missing pixels
    validation_split=0.2
)

aug_train_generator = aug_datagen.flow_from_directory(
    train_dir,
    target_size=(224, 224),
    batch_size=32,
    class_mode="categorical",
    subset="training"
)

aug_val_generator = aug_datagen.flow_from_directory(
    train_dir,
    target_size=(224, 224),
    batch_size=32,
    class_mode="categorical",
    subset="validation"
)

"""#Stratified K-Fold Cross-Validation Setup"""

from sklearn.model_selection import StratifiedKFold
import os

# Step 1: Get all image paths and labels
classes = os.listdir(train_dir)
image_paths = []
labels = []

for cls in classes:
    cls_folder = os.path.join(train_dir, cls)
    for img in os.listdir(cls_folder):
        image_paths.append(os.path.join(cls_folder, img))
        labels.append(cls)

df = pd.DataFrame({"filename": image_paths, "class": labels})

# Step 2: Define Stratified K-Fold
skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

IMG_SIZE = (224, 224)
BATCH_SIZE = 32

datagen = ImageDataGenerator(rescale=1./255)

fold = 1
for train_idx, val_idx in skf.split(df["filename"], df["class"]):
    print(f"\n--- Fold {fold} ---")

    train_df = df.iloc[train_idx]
    val_df = df.iloc[val_idx]

    # Step 3: Create Generators for each fold
    train_gen = datagen.flow_from_dataframe(
        train_df,
        x_col="filename",
        y_col="class",
        target_size=IMG_SIZE,
        class_mode="categorical",
        batch_size=BATCH_SIZE,
        shuffle=True
    )

    val_gen = datagen.flow_from_dataframe(
        val_df,
        x_col="filename",
        y_col="class",
        target_size=IMG_SIZE,
        class_mode="categorical",
        batch_size=BATCH_SIZE,
        shuffle=False
    )

    # 👉 Train your CNN model here for this fold
    fold += 1

"""# Visualizing Image Samples"""

# === Show RAW (original) images from a folder (no generator, no normalization) ===
# Set ROOT to the folder that contains your class subfolders.

import os, glob, numpy as np
from PIL import Image
import matplotlib.pyplot as plt
import random

def show_raw_images(ROOT, n=9, shuffle=True):
    exts = ('.jpg','.jpeg','.png','.bmp','.tif','.tiff')
    # collect all image paths under ROOT
    paths = [p for p in glob.glob(os.path.join(ROOT, "**", "*"), recursive=True)
             if p.lower().endswith(exts)]
    if not paths:
        raise FileNotFoundError(f"No images found under: {ROOT}")

    if shuffle:
        random.shuffle(paths)
    paths = paths[:n]

    cols = 3
    rows = (n + cols - 1) // cols
    plt.figure(figsize=(4*cols, 4*rows))
    for i, p in enumerate(paths, 1):
        im = Image.open(p)               # RAW file as-is (no normalization/augmentation)
        if im.mode == "RGBA": im = im.convert("RGB")
        arr = np.array(im)
        ax = plt.subplot(rows, cols, i)
        ax.imshow(arr, cmap="gray" if im.mode == "L" else None)
        ax.set_title(os.path.basename(os.path.dirname(p)), fontsize=9)  # class (parent folder)
        ax.axis("off")
    plt.tight_layout()
    plt.show()

# Example (Colab default from earlier steps):
# show_raw_images("/content/data/alz", n=9)
# Or set to your dataset path:
# show_raw_images("PATH/TO/YOUR/DATASET", n=9)

import matplotlib.pyplot as plt

x_batch, y_batch = next(aug_train_generator)

plt.figure(figsize=(10, 10))
for i in range(9):
    plt.subplot(3, 3, i+1)
    plt.imshow(x_batch[i])
    plt.axis("off")
plt.show()

# Function to visualize samples
def show_images(generator, title):
    x_batch, y_batch = next(generator)
    plt.figure(figsize=(10,10))
    for i in range(9):
        plt.subplot(3,3,i+1)
        plt.imshow(x_batch[i])
        plt.axis("off")
    plt.suptitle(title, fontsize=16)
    plt.show()

# Original normalized images
show_images(train_generator, "Sample Normalized Images")

# Augmented images
show_images(aug_train_generator, "Sample Augmented Images")

"""#Visualizing Class Distribution"""

def plot_bar_pie_from_df(df, label_col=None):
    # pick/derive label column
    if label_col is None:
        for c in ["label", "stage", "label_raw"]:
            if c in df.columns:
                label_col = c; break
    if label_col is None:
        if "image_path" not in df.columns:
            raise ValueError("Need 'label'/'stage'/'label_raw' or 'image_path' to infer labels.")
        df = df.copy()
        df["_label"] = df["image_path"].astype(str).apply(lambda p: os.path.basename(os.path.dirname(p)))
        label_col = "_label"

    counts = df[label_col].astype(str).value_counts().sort_index()

# PIE
plt.figure(figsize=(5,5))
plt.pie(df_counts['Image_Count'], labels=df_counts['Class'], autopct="%1.1f%%", startangle=90)
plt.title("Class Distribution")
plt.axis("equal"); plt.tight_layout(); plt.show()

# BAR
plt.figure(figsize=(7,4))
plt.bar(df_counts['Class'], df_counts['Image_Count'])
plt.title("Class Counts")
plt.xlabel("Class"); plt.ylabel("Count")
plt.xticks(rotation=15); plt.tight_layout(); plt.show()

"""# 📝 Conclusion

The dataset consists of four classes: Non-Demented, Very Mild Demented, Mild Demented, and Moderate Demented.

Dataset imbalance is evident: Non-Demented has the largest number of images, while Moderate Demented has comparatively fewer.

Applied standard image preprocessing:

Resizing all images to 224×224 pixels for consistency.

Normalization (scaling pixel values to [0,1]) for stable training.

Data Augmentation (rotation, shifts, zoom, flipping) to generate synthetic variations and reduce overfitting.

Implemented Stratified K-Fold cross-validation, ensuring balanced class representation across folds — this provides a more reliable evaluation than a single train/validation split.

Visual analysis (sample images, augmented images, class distribution plots) confirms that preprocessing steps are effective and dataset is ready for modeling
"""